config/routes.rb
Rails.application.routes.draw do
    resources :user, :articles, :store
    root 'top#main'
    get 'top/main', to: 'top#main'
    post 'top/login'
    get 'top/logout'
    get 'top/menu', to: 'top#menu'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/kodawari.rb
class Kodawari < ApplicationRecord
end

app/models/store.rb
class Store < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    private
     def current_user
       if session[:login_uid]
         User.find_by(email: session[:login_uid])
       end
     end
     helper_method :current_user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
      @articles = Article.all
    end
    
    def new
      @article = Article.new
      @store = Store.find(params[:store_id])
    end
    
    def create
      @article = Article.new(title: params[:article][:title], user_id: params[:article][:user_id], store_id: params[:article][:store_id],
                             intro: params[:article][:intro], kodawari: params[:article][:kodawari], mood: params[:article][:mood],
                             review: params[:article][:review])
      if @article.save
          flash[:notice] = '投稿しました。'
          redirect_to :root
      else
          render new_article_path
      end  
    end
    
    def destroy
      article = Article.find(params[:id])
      article.destroy
      redirect_to root_path  
    end
    
    def show
      @article = Article.find(params[:id])
    end
    
    def menu
      render 'menu'
    end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
    def index
       @stores = Store.all 
    end
    def new
       @store = Store.new
    end
    def create
       @store = Store.new(name: params[:store][:name], address: params[:store][:address], category_1: params[:store][:category_1], category_2: params[:store][:category_2])
       @store.save
       redirect_to '/store'
    end
    def edit
       @store = Store.find(params[:id])
    end
    def update
       @store = Store.update(name: params[:store][:name], address: params[:store][:address], category_1: [:store][:category_1], category_2: [:store][:category_2])
       redirect_to '/store'
    end
    def destroy
       store = Store.find(params[:id]) 
       store.destroy
       redirect_to '/store'
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
      if session[:login_uid]
        render 'main'
      else
        render 'login_form' 
      end
    end
    
    def menu
      render 'menu'
    end
    
    def login
      user = User.find_by(email: params[:email])
      if user and BCrypt::Password.new(user.pass) == params[:pass]
          flash[:notice] = 'ログインに成功しました。'
          session[:login_uid] = user.email
          redirect_to '/top/main'
      else
          flash[:notice] = 'ログインに失敗しました。'
          render 'login_form'
      end
    end
    
    def logout
      flash[:notice] = 'ログアウトに成功しました。'
      session.delete(:login_uid)
      redirect_to root_path
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def index
        @users = User.all
    end
    def new
        @user = User.new
    end
    def create
        pass = BCrypt::Password.create(params[:user][:pass])
        @user = User.new(email: params[:user][:email], pass: pass, belong: params[:user][:belong])
        if @user.save
            redirect_to '/top/main'
        else
            render 'new'
        end
    end
    def edit
        @user = User.find(params[:id])
    end
    def update
        user = User.find(params[:id])
        user.update(email: params[:user][:email], pass: params[:user][:pass], belong: params[:user][:belong])
        redirect_to '/user'
    end
    def destroy
        user = User.find(params[:id])
        user.destroy
        redirect_to '/user'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/articles/index.html.erb
<%= image_tag "logo.png" %><br>

<% if flash[:notice] %>
   <%= flash[:notice] %>
<% end %>

<div class="box">
    <% @articles.each do |article| %>
      <p><%= link_to "#{article.title}", "/articles/#{article.id}" %></p>
      <%= link_to '削除', "/articles/#{article.id}", method: :delete %>
    <% end %>
</div>

app/views/articles/new.html.erb
<%= image_tag "logo.png" %><br>

<%= form_with model: @article, url: {action: :create} do |f| %>
  <p>
  <%= f.hidden_field :store_id, :value => @store.id %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  </p>
  <p><%= f.label :title, 'タイトル' %>
  <%= f.text_field :title %></p>
  <p>店舗名:<%= @store.name %></p>
  <p>住所:<%= @store.address %></p>
  <p><%= f.label :intro, 'お店の紹介' %>
  <%= f.text_area :intro %></p>
  <p><%= f.label :kodawari, 'こだわり' %>
  <%= f.text_area :kodawari %></p>
  <p><%= f.label :mood, '雰囲気' %>
  <%= f.text_area :mood %></p>
  <p><%= f.label :review, 'レビュー' %>
  <%= f.text_area :review %></p>
  <p><%= f.submit '作成する' %></p>
<% end %>

app/views/articles/show.html.erb
<%= image_tag "logo.png" %><br>

<p>タイトル: <%= @article.title %></p>
<p><%= @article.intro %></p>
<p><%= @article.kodawari %></p>
<p><%= @article.mood %></p>
<p><%= @article.review %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gourmet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/store/edit.html.erb
<%= form_for @store, url: {action: :update} do |f| %>
  <%= f.label :name, 'name' %> 
  <%= f.text_field :name %> 
  <%= f.label :address, 'address' %> 
  <%= f.password_field :address %> 
  <%= f.label :category_1, 'category_1' %> 
  <%= f.text_field :category_1 %>
  <%= f.label :category_2, 'category_2' %> 
  <%= f.text_field :category_2 %>
  <%= f.submit '登録' %>
<% end %>

app/views/store/index.html.erb
<%= image_tag "logo.png" %><br>

<div class="box">
  <% @stores.each do |e| %>
    <p>
      <%= e.name %>
      <%= e.address %>
      <%= e.category_1 %>
      <%= e.category_2 %>
      <%= link_to '削除', store_path(e), method: :delete %>
      <%= link_to 'この店舗の記事を書く', new_article_path(store_id: e.id) %>
      </p>
  <% end %>
</div>

<p>
  <%= link_to '新規店舗追加', new_store_path %>
</p>

<p>
  <%= link_to '記事一覧', articles_path %>
</p>

app/views/store/new.html.erb
<%= image_tag "logo.png" %><br>

<% if @store.errors.present? %>
<h3> エラーがあります</h3>
<ul>
    <% @store.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
</ul>
<% end %>

<%= form_for @store, url: {action: :create} do |f| %>
  <%= f.label :name, 'name' %> 
  <%= f.text_field :name %> 
  <%= f.label :address, 'address' %> 
  <%= f.text_field :address %> 
  <%= f.label :category_1, 'category_1' %> 
  <%= f.text_field :category_1 %> 
  <%= f.label :category_2, 'category_2' %> 
  <%= f.text_field :category_2 %>
  <%= f.submit '登録' %>
<% end %>

app/views/top/login_form.html.erb
<% if flash[:notice] %>
   <%= flash[:notice] %>
<% end %>

<%= image_tag "logo.png" %><br>

<div class="box">
    <p>ようこそ！Gourmet notesへ！</p>
    
    <%= form_tag '/top/login', method: :post do %>
      <p><%= label_tag :email, 'メールアドレス' %>
      <%= text_field_tag :email %></p>
      <p><%= label_tag :pass, 'パスワード' %>
      <%= password_field_tag :pass %></p>
      <%= submit_tag 'ログイン' %>
    <% end %>
    <br/>
</div>

<p>
    <a><button class="logout"><%= link_to 'ユーザー一覧', '/user' %></button></a>
</p>

app/views/top/main.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <link rel="stylesheet" type="text/css" href="css/style.css">
        <link href="https://fonts.googleapis.com/css?family=Noto+Serif+JP|Open+Sans&display=swap" rel="stylesheet">
    </head>
    

<%= image_tag "logo.png" %><br>

<div class="box">
　<p>
 　 <a><button class="Button-style"><%= link_to '記事を書く', '/top/menu' %></button></a>
　  <a><button class="Button-style"><%= link_to '記事を見る', '/articles' %></button></a>
　</p>
</div>

<%= image_tag '' %>

<% if flash[:notice] %>
   <p><%= flash[:notice] %></p>
<% end %>

<% if session[:login_uid] %>
  <%= "#{session[:login_uid]}さんログイン中" %>
<% end %>

<br><button class="logout"><%= link_to 'ログアウト', top_logout_path %></button>

</html>

app/views/top/menu.html.erb
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <link rel="stylesheet" type="text/css" href="css/style.css">
        <link href="https://fonts.googleapis.com/css?family=Noto+Serif+JP|Open+Sans&display=swap" rel="stylesheet">
    </head>

<%= image_tag "logo.png" %><br>

<div class="box">
  <p>
     <a><button class="Button-style"><%= link_to '新しい記事を書く', '/store' %></button></a>
     <a><button class="Button-style"><%= link_to '作成済みの記事を編集する', '/articles' %></button></a>
  </p>
</div>

</html>

app/views/user/edit.html.erb
<%= image_tag "logo.png" %><br>

<%= form_for @user, url: {action: :update} do |f| %>
  <%= f.label :email, 'email' %> 
  <%= f.text_field :email %> 
  <%= f.label :pass, 'pass' %> 
  <%= f.password_field :pass %> 
  <%= f.label :belong, 'belong' %> 
  <%= f.text_field :belong %> 
  <%= f.submit '登録' %>
<% end %>

app/views/user/index.html.erb
<%= image_tag "logo.png" %><br>

<% @users.each do |e| %>
  <p>
    <%= e.email %>
    <%= e.pass %>
    <%= e.belong %>
    <%= link_to '削除', user_path(e), method: :delete %>
    </p>
<% end %>

<p>
  <%= link_to '新規ユーザ追加', new_user_path %>
</p>

<p>
  <%= link_to '投稿一覧', articles_path %>
</p>

app/views/user/new.html.erb
<%= image_tag "logo.png" %><br>

<% if @user.errors.present? %>
<h3> エラーがあります</h3>
<ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
</ul>
<% end %>


<%= form_for @user, url: {action: :create} do |f| %>
  <%= f.label :email, 'email' %> 
  <%= f.text_field :email %> 
  <%= f.label :pass, 'pass' %> 
  <%= f.password_field :pass %> 
  <%= f.label :belong, 'belong' %> 
  <%= f.text_field :belong %> 
  <%= f.submit '登録' %>
<% end %>